"""initial

Revision ID: 6076c42898d5
Revises: 
Create Date: 2026-02-25 21:19:42.550081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6076c42898d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especializaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especialista', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('horario', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('especializaciones')
    # ### end Alembic commands ###
